Studis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from student import views as views_student
from . import views as views_studis
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^osebje/', include('osebje.urls')),
    url(r'^misc/', include('miscellaneous.urls')),
    url(r'^student/',include('student.urls')),
    url(r'^vpis/',include('vpis.urls')),
    path('',include('authorization.urls')), #URL-ji za login, reset password...
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^students/$', views.StudentList.as_view(), name="api_student_list"),
    url(r'^students/(?P<pk>[0-9]+)/$', views.StudentDetail.as_view(), name="api_student_detail"),
    url(r'^profesors/$', views.ProfesorList.as_view(), name="api_profesor_list"),
    url(r'^profesors/(?P<pk>[0-9]+)/$', views.ProfesorDetail.as_view(), name="api_profesor_detail"),
    url(r'^subjects/$', views.PredmetList.as_view(), name="api_subject_list"),
    url(r'^subjects/(?P<pk>[0-9]+)/$', views.PredmetDetail.as_view(), name="api_subject_detail"),
    url(r'^splosni_predmeti/$', views.SplosniPredmetList.as_view(), name="api_splosni_predmeti_list"),
    url(r'^splosni_predmeti/(?P<pk>[0-9]+)/$', views.SplosniPredmetDetail.as_view(), name="api_splosni_predmeti_detail"),
    url(r'^modulski_predmeti/$', views.ModulskiPredmetList.as_view(), name="api_modulski_predmeti_list"),
    url(r'^modulski_predmeti/(?P<pk>[0-9]+)/$', views.ModulskiPredmetDetail.as_view(), name="api_modulski_predmeti_detail"),
    url(r'^strokovni_predmeti/$', views.StrokovnoIzbirniPredmetList.as_view(), name="api_strokovni_predmeti_list"),
    url(r'^strokovni_predmeti/(?P<pk>[0-9]+)/$', views.StrokovnoIzbirniPredmetDetail.as_view(), name="api_strokovni_predmeti_detail"),
    url(r'^splosno_izb_predmeti/$', views.SplosnoIzbirniPredmetList.as_view(), name="api_splosno_izb_predmeti_list"),
    url(r'^splosno_izb_predmeti/(?P<pk>[0-9]+)/$', views.SplosnoIzbirniPredmetDetail.as_view(), name="api_splosno_izb_predmeti_detail"),
    url(r'^vpisi_studenta/(?P<pk>[0-9]+)/$', views.VpisiStudentaDetail.as_view(), name='vpisi_studenta_detail'),
    url(r'^zetoni_studenta/(?P<pk>[0-9]+)/$', views.CoinStudentDetail.as_view(), name='zetoni_studenta_detail'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

osebje/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path
from . import views as osebje_views


urlpatterns = [
    # seznam studentov
    url(r'students/(?P<pk>[0-9]+)/$', osebje_views.StudentMulti, name="student_detail"),
    url(r'students/pdf/(?P<pk>[0-9]+)/$', osebje_views.generate_new_pdf_student, name="student_pdf_new"),
    url(r'indeks/pdf/(?P<pk>[0-9]+)/$', osebje_views.index_pdf, name="index_pdf"),
    url(r'indeks/csv/(?P<pk>[0-9]+)/$', osebje_views.index_csv, name="index_csv"),
    url(r'indeks1/pdf/(?P<pk>[0-9]+)/$', osebje_views.generate_new_pdf_student_kartoteka, name="generate_new_pdf_student_kartoteka"),
    url(r'indeks1/csv/(?P<pk>[0-9]+)/$', osebje_views.generate_new_csv_student_kartoteka, name="generate_new_csv_student_kartoteka"),
    url(r'students/csv/(?P<pk>[0-9]+)/$', osebje_views.generate_csv_student, name="student_csv"),
    url(r'students/pdf/$', osebje_views.generate_new_pdf, name="students_pdf"),
    url(r'students/csv/$', osebje_views.generate_csv_get_all, name="students_csv"),
    url(r'students/$', osebje_views.StudentList, name='student_list'),
    url(r'students_added/$', osebje_views.StudentAdded, name='student_added'),
    url(r'add_zeton/(?P<pk>[0-9]+)/$', osebje_views.AddZeton, name="student_add_zeton"),
    url(r'predmeti/$',osebje_views.predmet_list, name="predmet_list"),
    url(r'predmeti/(?P<pk>[0-9]+)/$', osebje_views.predmet_details, name="predmet_details"),
    url(r'predmeti/(?P<pk>[0-9]+)/vpisioceno/(?P<pk1>[0-9]+)/$', osebje_views.DirektenVpisOcene, name="DirektenVpisOcene"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenihIzpis/$', osebje_views.seznam_prijavljenih_izpis, name="seznam_prijavljenih_izpis"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenihIzpis/pdf$', osebje_views.seznam_prijavljenih_izpis_pdf, name="seznam_prijavljenih_izpis_pdf"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenihIzpis/csv$', osebje_views.seznam_prijavljenih_izpis_csv, name="seznam_prijavljenih_izpis_csv"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/$', osebje_views.seznam_prijavljenih, name="seznam_prijavljenih"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/(?P<pk2>[0-9]+)/$', osebje_views.seznam_prijavljenih_vpis, name="seznam_prijavljenih_vpis"),
    url(r'predmeti/csv/(?P<pk>[0-9]+)/$', osebje_views.generate_csv_predmeti, name="predmet_details_csv"),
    url(r'predmeti/pdf/(?P<pk>[0-9]+)/$', osebje_views.generate_pdf_predmeti, name="predmet_details_pdf"),
    url(r'potrdivpis/$', osebje_views.potrdi_vpis, name="potrdi_vpis"),
    url(r'NarocenaPotrdila/$', osebje_views.NarocenaPotrdila, name="NarocenaPotrdila"),
    url(r'NarocenaPotrdila/(?P<pk>[0-9]+)/$', osebje_views.NatisniNarocenaPotrdila, name="NatisniNarocenaPotrdila"),
    url(r'potrdivpis/(?P<pk>[0-9]+)/$', osebje_views.funkcija, name="potrdifunkcija"),
    url(r'potrdivpis/pdf/(?P<pk>[0-9]+)/$', osebje_views.potrdilo_vpis, name="natisnipotrdilo"),
    url(r'add_izpit/(?P<pk>[0-9]+)/$', osebje_views.AddIzpit, name="add_izpit"),
    url(r'kartoteka/(?P<pk>[0-9]+)/$', osebje_views.Kartoteka, name="kartoteka"),
    url(r'indeks/(?P<pk>[0-9]+)/$', osebje_views.Elektronski_Indeks, name="elektronski_indeks"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/odjavi/(?P<pk2>[0-9]+)/$',osebje_views.odjavistudent, name="odjavistudent"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/prijavi/(?P<pk2>[0-9]+)/$',osebje_views.prijavistudent, name="prijavistudent"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/prijavi/(?P<pk2>[0-9]+)/opozorilo/$',osebje_views.OpozoriloPrijava, name="OpozoriloPrijava"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/prijavi/(?P<pk2>[0-9]+)/opozorilo/nazaj/$',osebje_views.nazajPrijava, name="NazajPrijava"),
    url(r'predmeti/(?P<pk1>[0-9]+)/(?P<pk>[0-9]+)/seznamPrijavljenih/prijavi/(?P<pk2>[0-9]+)/opozorilo/potrdi/$',osebje_views.PotrjenaPrijava, name="PotrdiPrijava"),
    url(r'predmeti/(?P<pk>[0-9]+)/spremeni/(?P<pk1>[0-9]+)/$', osebje_views.SpremeniIzpit, name="spremeniIzpit"),
    url(r'predmeti/(?P<pk>[0-9]+)/spremeni/(?P<pk1>[0-9]+)/nazaj$', osebje_views.nazaj, name="nazaj"),
    url(r'predmeti/(?P<pk>[0-9]+)/izbrisi/(?P<pk1>[0-9]+)/$', osebje_views.BrisiIzpit, name="izbrisiIzpit"),
    url(r'predmeti/(?P<pk>[0-9]+)/izbrisi/(?P<pk1>[0-9]+)/opozorilo/$', osebje_views.OpozoriloIzpit, name="opozoriloIzpit"),
    url(r'predmeti/(?P<pk>[0-9]+)/izbrisi/(?P<pk1>[0-9]+)/opozorilo/nazaj/$', osebje_views.nazaj, name="nazaj"),
    url(r'predmeti/(?P<pk>[0-9]+)/izbrisi/(?P<pk1>[0-9]+)/opozorilo/potrdi/$', osebje_views.PotrjenBris, name="potrdi"),
    url(r'narocila/seznam', osebje_views.seznam_narocil, name="narocila_seznam"),

]

urlpatterns = format_suffix_patterns(urlpatterns)

Studis/models/storitve.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

class Coin(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    vrsta = models.ForeignKey('Vrsta_vpis', on_delete=models.CASCADE, blank = False)
    oblika = models.ForeignKey('Oblika_studij', on_delete=models.CASCADE, blank = False)
    nacin = models.ForeignKey('Nacin_studij', on_delete=models.CASCADE, blank = False)
    smer = models.ForeignKey('Smer', on_delete=models.CASCADE, blank = False)
    letnik = models.PositiveIntegerField(blank = False)
    pravica_izbire = models.BooleanField(blank = False)
    used = models.BooleanField(default = False)
    # kolicina = models.PositiveIntegerField()
    # datum = models.DateField()

class Evidenca_Vpis(models.Model):
    studijsko_leto = models.ForeignKey('Studijsko_leto', on_delete=models.CASCADE)
    st_vpisov = models.PositiveIntegerField(default=1)

class Studijsko_leto(models.Model):
    studijsko_leto = models.CharField(max_length = 9)

    def __str__(self):
        return "{}".format(self.studijsko_leto)

class Izpit(models.Model):
    predmet=models.ForeignKey('Predmet_leto', on_delete=models.CASCADE)
    datum=models.DateField(blank=False, null= False)
    cas = models.TimeField(blank=True, null= True)
    locked = models.BooleanField(default=False)
    izredni=models.BooleanField()
    prostor = models.CharField(max_length=100, blank=True, null= True)
    izprasevalec = models.ForeignKey('Profesor', on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.predmet.predmet.naslov_predmeta

    class Meta:
        ordering = ('datum',)


class Smer(models.Model): #vs,uni
    smer=models.CharField(unique=True,max_length=3)
    ime = models.CharField(max_length=50)
    sifra = models.CharField(max_length=7, blank=True, null=True)
    def __str__(self):
        return "{} - {}".format(self.sifra,self.ime)


class Nacin_studij(models.Model): #redni,izredni
    nacin=models.CharField(max_length=10,unique=True)
    sifra = models.CharField(max_length=1)
    def __str__(self):
        return "{} - {}".format(self.sifra,self.nacin)

class Oblika_studij(models.Model):
    oblika = models.CharField(max_length=20)
    sifra = models.CharField(max_length=1)
    def __str__(self):
        return "{} - {}".format(self.sifra,self.oblika)

class Vrsta_vpis(models.Model): # prvi vpis, ponavljanje, nadaljevanje, vpis po merilih...
    vrsta=models.CharField(max_length=50,unique=True)
    sifra = models.CharField(max_length=2)
    def __str__(self):
        return "{} - {}".format(self.sifra,self.vrsta)


class Evidenca_izpit(models.Model):
    student=models.ForeignKey('Student', on_delete=models.CASCADE)
    izpit=models.ForeignKey('Izpit', on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    ocena = models.PositiveIntegerField(blank=True, null=True)
    ocena_pisni = models.PositiveIntegerField(blank=True, null=True)
    tocke = models.PositiveIntegerField(blank=True, null=True)
    datum_odjave=models.CharField(max_length=100, blank=True, null= True)
    odjavitelj=models.CharField(max_length=100, blank=True, null= True)
    def __str__(self):
        return self.student.last_name+" "+self.izpit.predmet.predmet.naslov_predmeta


class Vpis(models.Model):
    letnik=models.PositiveIntegerField()
    leto_vpisa=models.ForeignKey('Studijsko_leto', on_delete=models.CASCADE)
    potrjen=models.BooleanField(blank=False, null=False, default=False)
    student=models.ForeignKey('Student', on_delete=models.CASCADE)
    smer=models.ForeignKey('Smer', on_delete=models.CASCADE)
    tip=models.ForeignKey('Nacin_studij', on_delete=models.CASCADE)
    vrsta=models.ForeignKey('Vrsta_vpis', on_delete=models.CASCADE)

    class Meta:
        ordering = ('leto_vpisa',)


class Evidenca_student(models.Model):
    student=models.ForeignKey('Student', on_delete=models.CASCADE)
    predmet=models.ForeignKey('Predmet_leto', on_delete=models.CASCADE)
    ocena=models.PositiveIntegerField(blank=True, null=True)
    letnik_predmeta=models.PositiveIntegerField()

    def __str__(self):
        # Če nima ocene, vrne v izpisu presledek
        return "{} {}".format(self.predmet.predmet.naslov_predmeta,str(self.ocena or ' '))



class Evidenca_profesor(models.Model):
    profesor=models.ForeignKey('Profesor',on_delete=models.CASCADE)
    predmet=models.ForeignKey('Predmet', on_delete=models.CASCADE)

    def __str__(self):
        return self.profesor.last_name+" "+self.predmet.naslov_predmeta


class Leto(models.Model):
    st_narejenih=models.PositiveIntegerField()
    studijsko_leto=models.CharField(max_length=25) #nevemo
    evidenca_student=models.ForeignKey('Evidenca_student', on_delete=models.CASCADE)

    def __str__(self):
        return self.evidenca_student.student.last_name+" "+self.studijsko_leto


class PotrdiloVpisa(models.Model):
    stevilka=models.PositiveIntegerField()


class SteviloOpravljanj(models.Model):
    student=models.ForeignKey('Student', on_delete=models.CASCADE)
    predmet=models.ForeignKey('Predmet',on_delete=models.CASCADE)
    stVseh=models.PositiveIntegerField(default=0)
    stPop=models.PositiveIntegerField(default=0)


class NarociloPotrdil(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    stevilo = models.IntegerField(default=1,
        validators=[MaxValueValidator(6), MinValueValidator(1)]
    )

    status = models.BooleanField(blank=False, null=False, default=True)
    datum_narocila = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.student + " " + self.stevilo + " " + self.status

osebje/models.py
from django.db import models

# Create your models here.

osebje/form_config/izpitni_rok/forms.py
from django import forms
import datetime
from Studis.validators import *
from Studis.error_messages import *
from Studis.models.subjects import Nosilci
from Studis.models.storitve import Vrsta_vpis, Nacin_studij, Smer, Oblika_studij, Izpit
import holidays
class IzpitForm(forms.Form):
    pk = None
    izprasevalec = forms.ModelChoiceField(queryset=Nosilci.objects.none(),empty_label = None)
    datum = forms.DateField(label="Datum izpita",initial=datetime.date.today)
    cas = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    prostor = forms.CharField(max_length=99)
    izredni = forms.BooleanField(label='Izredni izpit',required= False)
    def __init__(self, *args, **kwargs):
        if kwargs:
            self.pk = kwargs.pop('pk')
        super(IzpitForm, self).__init__(*args, **kwargs)
        nosilci = Nosilci.objects.filter(predmet_leto=self.pk)
        profesorji = [x.nosilec.id for x in nosilci]
        self.fields['izprasevalec'].queryset = Profesor.objects.filter(id__in=profesorji)
        


    def clean(self):
        cleaned_data = super().clean()
        datum = cleaned_data['datum']
        slovenia_holidays = holidays.CountryHoliday('SI') 
        izpiti_predmeta_datumi = Izpit.objects.filter(predmet_id=self.pk).values_list('datum',flat=True)
        if datum.weekday() >= 5 or datum <= datetime.date.today() or datum in slovenia_holidays or datum in izpiti_predmeta_datumi:
            raise forms.ValidationError("Izpitni rok ne sme biti v preteklosti, v soboto, nedeljo ali na praznik. Prav tako se ne sme podvajati po datumu.")
        return cleaned_data

class IzpitForm1(forms.Form):
    pk = None
    izprasevalec = forms.ModelChoiceField(queryset=Nosilci.objects.none(),empty_label = None)
    datum = forms.DateField(label="Datum izpita",initial=datetime.date.today)
    cas = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    prostor = forms.CharField(max_length=99)
    izredni = forms.BooleanField(label='Izredni izpit',required= False)
    def __init__(self, *args, **kwargs):
        if kwargs:
            self.pk = kwargs.pop('pk')
            self.izpit_pk = kwargs.pop('izpit_pk')
            print(self.izpit_pk)
        super(IzpitForm1, self).__init__(*args, **kwargs)
        nosilci = Nosilci.objects.filter(predmet_leto=self.pk)
        profesorji = [x.nosilec.id for x in nosilci]
        self.fields['izprasevalec'].queryset = Profesor.objects.filter(id__in=profesorji)
        


    def clean(self):
        cleaned_data = super().clean()
        datum = cleaned_data['datum']
        slovenia_holidays = holidays.CountryHoliday('SI') 
        izpiti_predmeta_datumi = Izpit.objects.filter(predmet_id=self.pk).values_list('datum',flat=True).exclude(id=self.izpit_pk)
        print(izpiti_predmeta_datumi)
        if datum.weekday() >= 5 or datum <= datetime.date.today() or datum in slovenia_holidays:
            raise forms.ValidationError("Izpitni rok ne sme biti v preteklosti, v soboto, nedeljo ali na praznik. Prav tako se ne sme podvajati po datumu.")
        return cleaned_data

osebje/form_config/ocene_tocke_izpit/forms.py
from django import forms
import datetime

from django.forms import inlineformset_factory

from Studis.validators import *
from Studis.error_messages import *
from Studis.models.storitve import Evidenca_izpit, Izpit

class IzpitOceneTockeForm(forms.Form):
    CHOICES = (
        (1, ("Vrnil")),
        (2, ("Ni vrnil"))
    )
    mail = forms.CharField(label='mail', required=False)
    tocke = forms.IntegerField(label='tocke', max_value=100, min_value=0, required=False)
    ocena_pisni = forms.IntegerField(label='ocena_pisni', max_value=10, min_value=1, required=False)
    ocena = forms.IntegerField(label='ocena', max_value=10, min_value=1, required=False)

    vrni_prijavo = forms.ChoiceField(choices=CHOICES, initial=2)


IzpitOceneTockeFormSet = inlineformset_factory(Izpit, Evidenca_izpit, fields=('student', 'tocke', 'ocena_pisni', 'ocena', 'status',), extra=10)

osebje/form_config/vpisi_student/forms.py
from django import forms

class UploadFileForm(forms.Form):
    datoteka=forms.FileField(label='datoteka')

osebje/templates/NarocenaPotrdila.html
{% extends 'base.html' %}
{% load rest_framework %}
{% load studis_extras %}
{% block title %} Seznam naročil {% endblock %}
{% block content %}

    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}

<div class="container-fluid">
<br>
<h1 class="display-4" style="font-size: 32px;">Čakajoča naročila</h1>
<a class="btn btn-primary" style="margin-bottom: 2px" href="/osebje/narocila/seznam/">Prenesi seznam naročil</a>
<br>
<table class="table table-hover" style="width:100%">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Vpisna številka</th>
            <th>Študent</th>
            <th>Datum naročila</th>
            <TH>Število naročenih izvodov</TH>
            <th>Natisni</th>
        </tr>
    </thead>
    <tbody>
        {% for vpis in narocila %}

                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ vpis.student.vpisna}}</td>
                    <td>{{ vpis.student.first_name}} {{ vpis.student.last_name}}</td>
                    <td>{{ vpis.datum_narocila|date:"d.m.Y" }}</td>
                    <td>{{ vpis.stevilo }}</td>
                    <td><a class="btn btn-primary" href="{{ vpis.student_id }}/?download=true"">Natisni</a></td>
                </tr>

        {% endfor %}
    </tbody>
</table>
<div>
    {% for error in errors %}
        <p class="danger">{{ error }}</p>
    {% endfor %}
</div>
</div>
{% endblock %}

osebje/templates/elektronski_indeks.html
{% extends 'base.html' %} {% load rest_framework %} {% load studis_extras %} {% block title %} Elektronski indeks {% endblock %} {% block content %}
<div class="container-fluid">
    <h1 class="display-4" style="font-size: 32px;">Elektronski indeks
        <br>
        <span style="font-size: 24px">{{ student.first_name }} {{ student.last_name }} ({{student.vpisna}})</span>
    </h1>

    <!-- <form method="get" class="form-inline">
        <div class="form-group">
            <select name="studijsko_leto" id="id_studijsko_leto" class="form-control mb-2 mr-sm-2">
                <option value="0" selected>Vsa študijska leta</option>
                <option value="1">2014/2015</option>
                <option value="2">2015/2016</option>
                <option value="3">2016/2017</option>
                <option value="4">2017/2018</option>
                <option value="5">2018/2019</option>
            </select>
        </div>
        <div class="form-group">
            <select name="polaganja" id="id_polaganja" class="form-control mb-2 mr-sm-2">
                <option value="0" selected>Vsa polaganja</option>
                <option value="1">Zadnja polaganja</option>
            </select>
        </div>
        <button class="btn btn-outline-primary mb-2 mr-sm-2" type="submit">Filtriraj po študijskem letu</button>
        <div class="dropdown">
            <button class="btn btn-outline-secondary mb-2 mr-sm-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Izvozi v
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/osebje/indeks/pdf/{{ student.id }}?{% url_replace %}">Pdf</a>
                <a class="dropdown-item" href="/osebje/indeks/csv/{{ student.id }}?{% url_replace %}">Excel</a>
            </div>
        </div>
    </form> -->
    <div class="dropdown">
        <button class="btn btn-outline-secondary mb-2 mr-sm-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Izvozi v
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/osebje/indeks/pdf/{{ student.id }}?{% url_replace %}/$">Pdf</a>
            <a class="dropdown-item" href="/osebje/indeks/csv/{{ student.id }}?{% url_replace %}/$">Excel</a>
        </div>
    </div>
    <hr style="margin-top: 5px;"> 
    

    <div class="">
        <table class="table table-hover" style="width:100%; font-size: 0.9em;">
            <thead class="thead-dark">
                <tr>
                    <th style="width:4%">#</th>
                    <th>Šifra</th>
                    <th>Naziv predmeta</th>
                    <th>Ocenil</th>
                    <th>Datum</th>
                    <th>Opravljanje</th>
                    <th>ECTS</th>
                    <th>Ocena</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in izpiti %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ entry.izpit.predmet.predmet.sifra}}</td>
                    <td>{{ entry.izpit.predmet.predmet.naslov_predmeta}}</td>
                    <td>{{ entry.izpit.predmet.profesor.first_name}} {{ entry.izpit.predmet.profesor.last_name}}</td>
                    <td>{{ entry.izpit.datum|date:"d.m.Y"}}</td>
                    <td> {% with opr|index:forloop.counter0 as st %}
                        {{ st.stVseh }}
                    {% endwith %} </td>
                    <td>{{ entry.izpit.predmet.predmet.kreditne_tocke}}</td>
                    <td>{{ entry.ocena}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <br>
    <h1 class="display-5" style="font-size: 24px;">Povprečne ocene po študijskih letih</h1>
    <hr>
    <div class="">
        <table class="table table-hover" style="width:100%; font-size: 0.9em;">
            <thead class="thead-dark">
                <tr>
                    <th style="width:4%">#</th>
                    <th>Študijsko leto</th>
                    <th>Število opravljenih izpitov</th>
                    <th>Kreditne točke</th>
                    <th>Skupno povprečje</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in data %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ entry.0.leto_vpisa.studijsko_leto}}</td>
                    <td>{{ entry.2|length}}</td>
                    <td>{{ entry.1.ECTS}}</td>
                    <td>{{ entry.1.avg}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <br>

    <br>
    <h1 class="display-5" style="font-size: 24px;">Skupna povprečna ocena</h1>
    <hr>
    <div class="">
        <table class="table table-hover" style="width:100%; font-size: 0.9em;">
            <thead class="thead-dark">
                <tr>
                    <th>Število opravljenih izpitov</th>
                    <th>Kreditne točke</th>
                    <th>Skupno povprečje</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ globalOcena.len}}</td>
                    <td>{{ globalOcena.ECTS}}</td>
                    <td>{{ globalOcena.avg}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %} 

osebje/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gs</title>
</head>
<body>

</body>
</html>