Studis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from student import views as views_student
from . import views as views_studis
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^osebje/', include('osebje.urls')),
    url(r'^misc/', include('miscellaneous.urls')),
    url(r'^student/',include('student.urls')),
    url(r'^vpis/',include('vpis.urls')),
    path('',include('authorization.urls')), #URL-ji za login, reset password...
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^students/$', views.StudentList.as_view(), name="api_student_list"),
    url(r'^students/(?P<pk>[0-9]+)/$', views.StudentDetail.as_view(), name="api_student_detail"),
    url(r'^profesors/$', views.ProfesorList.as_view(), name="api_profesor_list"),
    url(r'^profesors/(?P<pk>[0-9]+)/$', views.ProfesorDetail.as_view(), name="api_profesor_detail"),
    url(r'^subjects/$', views.PredmetList.as_view(), name="api_subject_list"),
    url(r'^subjects/(?P<pk>[0-9]+)/$', views.PredmetDetail.as_view(), name="api_subject_detail"),
    url(r'^splosni_predmeti/$', views.SplosniPredmetList.as_view(), name="api_splosni_predmeti_list"),
    url(r'^splosni_predmeti/(?P<pk>[0-9]+)/$', views.SplosniPredmetDetail.as_view(), name="api_splosni_predmeti_detail"),
    url(r'^modulski_predmeti/$', views.ModulskiPredmetList.as_view(), name="api_modulski_predmeti_list"),
    url(r'^modulski_predmeti/(?P<pk>[0-9]+)/$', views.ModulskiPredmetDetail.as_view(), name="api_modulski_predmeti_detail"),
    url(r'^strokovni_predmeti/$', views.StrokovnoIzbirniPredmetList.as_view(), name="api_strokovni_predmeti_list"),
    url(r'^strokovni_predmeti/(?P<pk>[0-9]+)/$', views.StrokovnoIzbirniPredmetDetail.as_view(), name="api_strokovni_predmeti_detail"),
    url(r'^splosno_izb_predmeti/$', views.SplosnoIzbirniPredmetList.as_view(), name="api_splosno_izb_predmeti_list"),
    url(r'^splosno_izb_predmeti/(?P<pk>[0-9]+)/$', views.SplosnoIzbirniPredmetDetail.as_view(), name="api_splosno_izb_predmeti_detail"),
    url(r'^vpisi_studenta/(?P<pk>[0-9]+)/$', views.VpisiStudentaDetail.as_view(), name='vpisi_studenta_detail'),
    url(r'^zetoni_studenta/(?P<pk>[0-9]+)/$', views.CoinStudentDetail.as_view(), name='zetoni_studenta_detail'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

student/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path
from . import views as student_views

urlpatterns = [
    #url(r'^(?P<pk>[0-9]+)/$', student_views.StudentMulti, name="student_detail"),
    url(r'^predmeti/$', student_views.SubjectList, name="subject_list"),
    url(r'^predmeti/prijavi/(?P<pk>[0-9]+)/$', student_views.PrijaviIzpit, name="PrijaviIzpit"),
    url(r'^predmeti/odjavi/(?P<pk>[0-9]+)/$', student_views.OdjaviIzpit, name="OdjaviIzpit"),
    url(r'account/$', student_views.account_details, name="acc_detail"),
    url(r'account/pdf/(?P<pk>[0-9]+)/$', student_views.generate_new_pdf_student, name="acc_detail_pdf"),
    url(r'account/csv/(?P<pk>[0-9]+)/$', student_views.generate_csv_student, name="acc_detail_csv"),
    url(r'account/kartoteka/$',student_views.kartoteka_detail, name="kartoteka_detail"), 
    url(r'account/indeks/$',student_views.indeks_detail, name="indeks_detail"),
    url(r'naroci/potrdilo/$',student_views.naroci_potrdilo, name="naroci_potrdilo")
]

urlpatterns = format_suffix_patterns(urlpatterns)

student/models.py
from django.db import models

# Create your models here.

student/form_config/narocil_potrdila/forms.py
from django import forms

MY_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)

class NarociloForms(forms.Form):
    stevilo = forms.ChoiceField(choices=MY_CHOICES)

student/form_config/urejanje_studenta/forms.py
from django import forms
import datetime
from Studis.models import Posta, Drzava, Spol

class VpisForm(forms.Form):
    first_name = forms.CharField(label='Ime', max_length=100)
    last_name = forms.CharField(label='Priimek', max_length=100)
    emso = forms.CharField(label='Emšo', max_length=13)
    datum_rojstva = forms.CharField(initial=datetime.datetime.now().strftime("%d.%m.%Y"), label='datum_rojstva')
    drzava = forms.ModelChoiceField(label="Država", queryset=Drzava.objects.all())
    spol=forms.ModelChoiceField(label='Spol', queryset=Spol.objects.all())
    tel = forms.CharField(label='Telefonska številka', max_length=15)
    ulica_prejem = forms.CharField(label='Ulica', max_length=50)
    posta_prejem = forms.ModelChoiceField(queryset=Posta.objects.all() ,widget=forms.Select(attrs={'class':'custom-select'}))
    #def clean_datum_rojstva(self):
        #datum_rojstva= self.cleaned_data.get('datum_rojstva')
        #dt = datetime.datetime.strptime(datum_rojstva, "%d.%m.%Y")
        #print(dt.strftime("%Y-%m-%d"))
        #return dt.strftime("%Y-%m-%d")

student/views.py
import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from Studis.models.users import Student
from Studis.models.storitve import Coin, NarociloPotrdil
from Studis.models.subjects import Predmet, Predmet_leto
from Studis.models.storitve import Evidenca_student, Izpit, Coin, Evidenca_izpit, Vpis, Studijsko_leto, SteviloOpravljanj
from Studis.models import User
from api.serializers import StudentSerializer
from django.shortcuts import redirect

from student.form_config.narocil_potrdila.forms import NarociloForms
from .form_config.urejanje_studenta.forms import VpisForm as VpisFormaUrejanjeStudenta
from Studis.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from decorators import *
from django.template.loader import get_template
from django.http import HttpResponse
import csv
import datetime
from datetime import date, timedelta
from osebje.views import date_filter
from .exporter.student_printing import MyPrint as MyPrintStudent
from io import BytesIO
from django.contrib import messages
from django.db.models import Max
from django.shortcuts import render_to_response
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

@login_required
@user_passes_test(is_student)
def account_details(request):
    user = request.user
    if request.method == 'GET':
        student = Student.objects.select_related('posta_prejem','posta_naslov').get(pk=user.id)
        vpisi = student.vpis_set.all().select_related()
        Obstaja=False
        try:
            zeton = Coin.objects.filter(student=request.user.pk).last()
            Obstaja=True
            if zeton.used:
                Obstaja=False
        except:
            Obstaja=False
        return render(request, 'student_details.html', {'student': student, 'vpisi' : vpisi, 'je': Obstaja})

@login_required
@user_passes_test(is_student)
def SubjectList(request):
    predmeti = []
    for evidenca in Evidenca_student.objects.prefetch_related("predmet__predmet").filter(student=request.user).values("predmet__predmet__naslov_predmeta", "predmet__predmet__sifra").distinct():
        predmeti.append([evidenca["predmet__predmet__naslov_predmeta"], evidenca["predmet__predmet__sifra"]])
    student=request.user

    student1 = Student.objects.select_related('posta_prejem', 'posta_naslov').get(pk=student.id)
    vpisi = student1.vpis_set.all().select_related().last()
    #print(vpisi.leto_vpisa)
    vpisani_predmeti = []
    if vpisi is not None:
        vpisani_predmeti = Evidenca_student.objects.filter(predmet__studijsko_leto=vpisi.leto_vpisa,student=student)
    #print(vpisani_predmeti)
    vpisani_predmeti1=[o.predmet for o in vpisani_predmeti]
    """names_to_exclude_pon1 = [o.predmet for o in ponovno1]
    #print(names_to_exclude_pon1)
    names_to_exclude_pon2 = [o.predmet for o in ponovno2]
    #print(names_to_exclude_pon2)"""
    leto = Studijsko_leto.objects.all()
    #print(leto[2])
    #print(leto[3])

    if vpisi is None:
        vpisani_predmeti = Evidenca_student.objects.filter(student=student)
    else:
        vpisani_predmeti = Evidenca_student.objects.filter(student=student)
        max=0
        for x in vpisani_predmeti:
            if max < x.predmet.studijsko_leto.pk:
                max=x.predmet.studijsko_leto.pk
        vpisani_predmeti = Evidenca_student.objects.filter(predmet__studijsko_leto_id=max,student=student)


    vpisani_predmeti1=[o.predmet for o in vpisani_predmeti]

    leto = Studijsko_leto.objects.all()
    izpiti=[]
    for predmet in vpisani_predmeti1:
        tmp = Predmet_leto.objects.select_related('predmet', 'profesor', 'studijsko_leto').get(pk=predmet.pk)
        izpittmp = Izpit.objects.select_related().filter(predmet=tmp.pk, locked=False).filter(evidenca_izpit__ocena__isnull=True)
        if izpittmp.count() > 0:
            izpiti+=izpittmp
    izpiti1=[]
    datum_danes = datetime.date.today()
    for x in izpiti:
        if x not in izpiti1 and x.datum >= datum_danes:
            izpiti1.append(x)
    #print(izpiti1)
    #print(izpiti)
    izpiti1.sort(key=lambda x: x.datum)


    datumi=date_filter(izpiti)
    datumi=datumi[::-1]
    #datumi=date_filter(izpiti1)
    #datumi=datumi[::-1]
    #print(datumi)

    prijavljen=Evidenca_izpit.objects.filter(student=student).filter(ocena__isnull=True)
    prijavljeni=[]
    blockOstaliRok=[]
    for x in prijavljen:
        if x.izpit.predmet not in blockOstaliRok and x.status==True:
            blockOstaliRok.append(x.izpit.predmet)
        if x.status == True:
            prijavljeni.append(x.izpit)
    return render(request,"mysubjects.html", {'predmeti':vpisani_predmeti, 'izpiti':izpiti1, 'prijavljen':prijavljeni, 'blokiraj':blockOstaliRok, 'evidenca':vpisani_predmeti})# ,'datumi':datumi})

#uporabljen
def generate_new_pdf_student(request, pk):
    student = Student.objects.select_related('posta_prejem', 'posta_naslov').get(pk=pk)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="%s.pdf"' %(student.vpisna)
    buffer = BytesIO()
    report = MyPrintStudent(buffer, 'Letter', pk)
    pdf = report.print_users()
    response.write(pdf)
    return response

#uporabljen
def generate_csv_student(request, pk):
    student = Student.objects.select_related('posta_prejem', 'posta_naslov').get(pk=pk)
    vpisi = student.vpis_set.all().select_related()
    response = HttpResponse(content_type='text/csv')
    filename = "Student_%s.csv" % (student.vpisna)
    response['Content-Disposition'] = 'attachment; filename="%s"' % (filename)

    response.write(u'\ufeff'.encode('utf8'))
    writer = csv.writer(response)
    date = datetime.date.today()
    writer.writerow(['Datum izpisa', date])
    writer.writerow([])
    writer.writerow([])
    writer.writerow([])
    writer.writerow(['Osebni podatki študenta'])
    writer.writerow(['Ime', student.first_name])
    writer.writerow(['Priimek', student.last_name])
    writer.writerow(['Vpisna številka', student.vpisna])
    writer.writerow(['Univerzitetni e-mail', student.email])
    writer.writerow(['Telefonska številka', student.tel])
    writer.writerow(['Osebni e-mail', student.osebni_email])
    writer.writerow([''])
    writer.writerow([''])

    writer.writerow(['Naslov stalnega prebivališča'])
    writer.writerow(['Stalno prebivališče - Država', student.posta_naslov.drzava])
    writer.writerow(['Stalno prebivališče - Ulica', student.ulica_naslov])
    writer.writerow(['Stalno prebivališče - Pošta', student.posta_naslov.postna_stevilka])
    writer.writerow(['Stalno prebivališče - Kraj', student.posta_naslov.kraj])
    writer.writerow([''])
    writer.writerow([''])

    writer.writerow(['Naslov za dostavo pošte'])
    writer.writerow(['Prejem - Država', student.posta_prejem.drzava])
    writer.writerow(['Prejem - Ulica', student.ulica_prejem])
    writer.writerow(['Prejem - Pošta', student.posta_prejem.postna_stevilka])
    writer.writerow(['Prejem - Kraj', student.posta_prejem.kraj])
    writer.writerow([''])
    writer.writerow([''])

    if vpisi:
        writer.writerow(['Podatki o vpisih'])
        for vpis in vpisi:
            writer.writerow(['Študijsko leto',vpis.leto_vpisa.studijsko_leto])
            writer.writerow(['Letnik',vpis.leto_vpisa.studijsko_leto])
            writer.writerow(['Študijski program',vpis.leto_vpisa.studijsko_leto])
            writer.writerow(['Vrsta vpisa',vpis.leto_vpisa.studijsko_leto])
            writer.writerow(['Način študija',vpis.leto_vpisa.studijsko_leto])
            writer.writerow([''])

    return response

def PrijaviIzpit(request,pk):
    student1=request.user.id
    student=Student.objects.filter(pk=student1)
    izpit=Izpit.objects.filter(pk=pk).get()
    coin=Coin.objects.filter(student=student1).last()

    #print(coin.vrsta.id)
    stOpravljanjLetos = Evidenca_izpit.objects.filter(izpit__predmet=izpit.predmet,student=student[0],ocena__isnull=False).count()
    stVsehOpravljanj =Evidenca_izpit.objects.filter(izpit__predmet__predmet=izpit.predmet.predmet,student=student[0],ocena__isnull=False).count()
    print("stopravljanj letos")
    #print(stOpravljanjLetos)
    #print("stopravljanj vseh")
    #print(stVsehOpravljanj)
    if coin.vrsta.id == 2:
        stVsehOpravljanj=stOpravljanjLetos
    xxx = Student.objects.select_related('posta_prejem', 'posta_naslov').get(pk=request.user.id)
    vpisi = xxx.vpis_set.all().select_related().last()
    izredni=vpisi.tip.sifra
    #print(izredni)
    zadnjaocena= Evidenca_izpit.objects.filter(izpit__predmet=izpit.predmet,student=student[0],ocena__gt=5).count()
    #print(zadnjaocena)
    stOpravljanjLetos=Evidenca_izpit.objects.filter(izpit__predmet=izpit.predmet,student=student[0],ocena__isnull=False).count()
    stDejanskihOpravljanj=SteviloOpravljanj.objects.filter(student=student[0],predmet=izpit.predmet.predmet).last().stVseh
    stPopravljanj=SteviloOpravljanj.objects.filter(student=student[0],predmet=izpit.predmet.predmet).last().stPop
    stVeljavnihOpravljanj=stDejanskihOpravljanj-stPopravljanj

    xxx = Student.objects.select_related('posta_prejem', 'posta_naslov').get(pk=request.user.id)
    vpisi = xxx.vpis_set.all().select_related().last()
    if vpisi is None:
        leto_vpisa='0'
    else:
        leto_vpisa=vpisi.leto_vpisa
    leto_predmeta=izpit.predmet.studijsko_leto

    izredni=1
    if leto_predmeta != leto_vpisa:
        izredni=3
        message = str("Nevpisan študent.")
        messages.success(request, message)

    #omejitev prijave 2 dni prej
    datum_in_2_days = (datetime.datetime.now() + timedelta(days=2)).strftime("%Y-%m-%d")
    datum_izpita=izpit.datum.strftime("%Y-%m-%d")
    if zadnjaocena == 0:

student/templates/mysubjects.html
{% extends 'base.html' %}
{% load rest_framework %}
{% load studis_extras %}
{% block title %} Predmet List {% endblock %}

{% block content %}
<style>
.rdec {background-color: #f44336;}
</style>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}

<div class="container-fluid">
    <h3>Pregled vseh predmetov</h3>
    <div>
        <table class="table table-hover" style="width:100%">
            <thead class="thead-dark">
                <tr>
                    <th>Šifra</th>
                    <th>Naslov predmeta</th>
                    <th>Ocena</th>
                </tr>

            </thead>
            <tbody>
                {% for predmet in predmeti  %}

                    <tr>
                        <td>{{ predmet.predmet.predmet.sifra }}</td>
                        <td>{{ predmet.predmet}}</td>
                        {% if predmet.ocena  %}<td>{{ predmet.ocena }}</td>{% else %}<td></td>{% endif %}
                    </tr>

                {% endfor %}
            </tbody>
        </table>
    <h3>Razpisani izpitni roki</h3>
        <table class="table table-hover" style="width:100%">
            <thead class="thead-dark">
                <tr>
                    <th>Letnik</th>
                    <th>Predmet</th>
                    <th>Izvajalec</th>
                    <th>Datum</th>
                    <th>Prijava/Odjava</th>
                </tr>

            </thead>
            <tbody>
                {% for izpit in izpiti %}
                    <tr>
                        {% for evi in evidenca %}
                            {% if evi.predmet == izpit.predmet %}
                                <td>{{ evi.letnik_predmeta }}</td>
                                {{ "<!--" }}
                            {% endif %}
                        {% endfor %}
                        {{ "-->" }}
                        <td>{{ izpit.predmet }} </td>
                        <td>{{ izpit.predmet.profesor.first_name }} {{ izpit.predmet.profesor.last_name }} </td>
                        <td>{{ izpit.datum|date:"d.m.Y" }}</td>
                        <td>
                            {% if izpit in prijavljen %}
                                    <a class="btn btn-primary rdec" color="red" href="{% url 'OdjaviIzpit' izpit.id%}">Odjavi</a>
                            {% else %}
                                {% if izpit.predmet in blokiraj %}
                                    <a class="btn btn-primary disabled"  href="{% url 'PrijaviIzpit' izpit.id%}">Prijavi</a>
                                {% else %}
                                    <a class="btn btn-primary" href="{% url 'PrijaviIzpit' izpit.id%}">Prijavi</a>
                                {% endif %}
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
    <script>
        if (message > 0){
            alert('{{ message }}');
        }
    </script>
{% endblock %}

student/templates/naroci_potrdilo.html
{% extends 'base.html' %}
{% load rest_framework %}
{% load studis_extras %}
{% block title %} Naročilo potrdila o vpisu {% endblock %}

{% block content %}
    <div class="container-fluid">
        <h3>Naročilo potrdila o vpisu</h3>
        <div class="col-md-12 text-center">
            <form action="/student/naroci/potrdilo/" method="post">
                {% csrf_token %}
                <table class="table table-hover col-md-6" style="width:100%">
                    <thead class="thead-dark">
                        <tr>
                            <th>Vrsta vpisa</th>
                            <th>Število potrdil</th>
                            <th>Pošlji</th>
                        </tr>

                    </thead>
                    <tbody>

                        <tr>
                            {% if vrsta is not None %}
                                <td>{{ vrsta }}</td>
                            {% else %}
                                <td>Ni vpisa</td>
                            {% endif %}
                            <td><select name="stevilo" id="id_stevilo" class="form-control">
                              <option value="1">1</option>

                              <option value="2">2</option>

                              <option value="3">3</option>

                              <option value="4">4</option>

                              <option value="5">5</option>

                              <option value="6">6</option>

                            </select></td>
                            <td>
                                {% if omogoci is True and vrsta is not None %}
                                    <input class="btn btn-primary" type="submit" value="Dodaj" />
                                {% else %}
                                    <input disabled class="btn btn-primary" type="submit" value="Dodaj" />
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

student/templates/student_details_pdf.html
{% load rest_framework %}
{% load studis_extras %}
{% block content %}

<h1 class="display-4" style="font-size: 24px;" align="center">Podatki o študentu</h1>
<hr>
<br>
<div class="container-fluid">
    <h1 class="display-4" style="font-size: 16px;">Splošni podatki</h1>
    <br>
    <table class="table table-hover" style="max-width:40%">
        <tbody>    
            <tr>
                <td> <h6>Ime</h6></td>
                <td> {{ student.first_name }} </td>
            </tr>
            <tr>
                <td> <h6>Priimek</h6></td>
                <td> {{ student.last_name }} </td>
            </tr>
            <tr>
                <td> <h6>Vpisna številka</h6></td>
                <td> {{ student.vpisna }}</td>
            </tr>
            <tr>
                <td> <h6>Univerzitetni e-mail</h6></td>
                <td> {{ student.email }} </td>
            </tr>
            <tr>
                <td> <h6>Tel. številka</h6></td>
                <td> {{ student.tel }} </td>
            </tr>
            <tr>
                <td> <h6>Osebni e-mail</h6></td>
                <td> {{ student.osebni_email }} </td>
            </tr>
        </tbody>
    </table>
</div>
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4">
            <h1 class="display-4" style="font-size: 16px;">Naslov stalnega bivališča</h1>
            <br>    
            <table class="table table-hover" style="max-width:70%">
                <tbody>
                    <tr>
                        <td> <h6>Država</h6></td>
                        <td> {{ student.posta_naslov.drzava }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Ulica</h6></td>
                        <td> {{ student.ulica_naslov }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Pošta</h6></td>
                        <td> {{ student.posta_naslov.postna_stevilka }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Kraj</h6></td>
                        <td> {{ student.posta_naslov.kraj }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-lg-6">
            <h1 class="display-4" style="font-size: 16px;">Naslov za dostavo pošte</h1>
            <br>
            <table class="table table-hover" style="max-width:50%">
                <tbody>
                    <tr>
                        <td> <h6>Država</h6></td>
                        <td> {{ student.posta_prejem.drzava }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Ulica</h6></td>
                        <td> {{ student.ulica_prejem }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Pošta</h6></td>
                        <td> {{ student.posta_prejem.postna_stevilka }}</td>
                    </tr>
                    <tr>
                        <td> <h6>Kraj</h6></td>
                        <td> {{ student.posta_prejem.kraj }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="container-fluid">
            <br>
            <h1 class="display-4" style="font-size: 16px;">Podatki o vpisih</h1>
            <table class="table table-hover" style="width:100%">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>Študijsko leto</th>
                        <TH>Letnik</TH>
                        <th>Študijski program</th>
                        <th>Vrsta vpisa</th>
                        <th>Način študija</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for vpis in vpisi %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ vpis.leto_vpisa.studijsko_leto }}</td>
                        <td>{{ vpis.letnik }}</td>
                        <td>{{ vpis.smer.ime }}</td>
                        <td>{{ vpis.vrsta.vrsta }}</td>
                        <td>{{ vpis.tip.nacin }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
    
{% endblock %}

student/templates/urejanje_studenta.html
{% extends 'base.html' %}
    {% block title %}Pregled{% endblock %}
    {% block content %}
        {% load rest_framework %}
        <div class="container py-5">
          <div class="row">
            <div class="col-md-8 offset-md-2">
              <div class="card" id="pregled_card">
                <div class="card-header">
                  <h3 class="mb-0">Pregled študenta: {{ students.first_name }} {{ students.last_name }}</h3>
                </div>
                  <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != "vpisna" and field.name != "email" %}
                                <div class="form-group">
                                    <label for="{{ field.name }}" ><b>{{ field.label_tag }}</b></label>
                                    {{ field|add_class:"form-control login_input" }}
                                </div>
                                <div class="form-group has-errors text-danger small">
                                    {{field.errors}}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <input class="btn btn-primary" type="submit" value="Submit" />
                    </form>
                  </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}